sudo: required

language: go
go:
- 1.10.x
- master

services:
- docker

go_import_path: github.com/improbable-eng/thanos

install:
- make install-tools
- dep ensure

script:
- make format test

after_success:
- if [ "$TRAVIS_BRANCH" == "V3ckt0r/travis-ci" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  fi
- cd $HOME/gopath/src/github.com/improbable-eng/thanos
- docker build -t vect0r/thanos .
- docker push vect0r/thanos
