sudo: required

language: go
go:
- 1.10.x
- master

services:
- docker

go_import_path: github.com/improbable-eng/thanos

install:
- make install-tools
- dep ensure

script:
- make format test
- make docker

after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  fi
- cd $HOME/gopath/src/github.com/improbable-eng/thanos
- make docker-push
